.\" Process this file with
.\" groff -man -Tutf8 betaradio.1
.\"
.TH BETARADIO 1 "2010-10-08" GNU "BetaRadio User Manuals"
.SH NAME
betaradio \- hiChannel internet radio client on GNU/Linux
.SH DESCRIPTION
.B betaradio
With this client you can listen to hiChannel radio and PTT Radio without
opening a browser. It displays a icon on system tray that you can click and
select the channel you want to listen to.
.SH AUTHOR
Shin-Yuan Lee (FourDollars) <fourdollars@gmail.com>
