.\" Process this file with
.\" groff -man -Tutf8 betaradio.1
.\"
.TH BETARADIO 1 "2010-06-26" GNU "BetaRadio User Manuals"
.SH NAME
betaradio \- hiChannel internet radio client on GNU/Linux
.SH DESCRIPTION
.B betaradio
with this client you can listen to the hiChannel internet radio without
opening a browser. It displays an icon on system tray that you can click and
select the channel you want to listen to.
.SH AUTHOR
Shin-Yuan Lee (FourDollars) <fourdollars@gmail.com>
